### ISSUE TITLE
Add donation link

### ISSUE THREAD

**Issue by samdidos** [ClubCedille/clubcedille.github.io#11]
FDETS creates a direct link to allow donators to access a auto-generated form to give money to our club (available at http://www.etsmtl.ca/fdets/etudiants/Sollicitation). We have to insert a link to this page on our site.

The link : https://www.jedonneenligne.org/fdets/index.php?FrmUID=75&FrmActUID1922=tyC4celGNuDLm%2BWJHk6urw%3D%3D

**Comment by samdidos** [comment]
This is a simple task but it has to be done soon. just put one of those images : https://drive.google.com/open?id=0B58H_VwAPaA5OUtPSVZBaURsX0U
at the bottom of the site and put this link :
https://www.jedonneenligne.org/fdets/index.php?FrmUID=75&FrmActUID1922=tyC4celGNuDLm%2BWJHk6urw%3D%3D
so it could redirect at the donation form when someone clicks on the page.

**Comment by samdidos** [comment]
Ok I added it but it's not pretty loll

**Comment by ygotame** [comment]
I will try to improve this when I have few moments

**Comment by samdidos** [comment]
The image link is working but the image create a bug in the mobile version. We need to let the image shrink so it could be adapted to the width.

**Comment by samdidos** [comment]
All good now
