### ISSUE TITLE
Add Club Members to Member List

### ISSUE THREAD

**Issue by RikuAvelar** [ClubCedille/clubcedille.github.io#2]

**Comment by samdidos** [comment]
We have to ask pictures of the new members so we can add them to the site.

**Comment by mosieurlaurin** [comment]
And add me to old members!!

**Comment by ygotame** [comment]
J'ai mis @mosieurlaurin dans la liste des anciens membres. J'ai aussi ajouté @StrikWolf  et moi-même évidement :) dans la liste des membres. On ajoutera d'autres personnes au fur à mesure qu'on aura les photos.

**Comment by samdidos** [comment]
Merci @ygotame ! Juste petit detail, il faudrait ajouter "cofondateur" a la description de Patrick, cest un oubli j'imagine

**Comment by ygotame** [comment]
Done
