### ISSUE TITLE
Add new members in the list

### ISSUE THREAD

**Issue by ygotame** [ClubCedille/clubcedille.github.io#27]
Add new members in the list

**Comment by AXDOOMER** [comment]
En enlever ceux qui ne sont plus là

**Comment by AXDOOMER** [comment]
Je suggère qu'on enlève les photos des anciens membres. 

Les photos des nouveaux membres seront ajoutées après 6 ou 8 mois.

**Comment by AXDOOMER** [comment]
La procédure pour ajouter un membre dans les photos est la suivante:

1. Ajouter une photo dans `img/team/`, comme par exemple ` img/team/alexandre.jpg` où "alexandre" est le nom à utiliser pour la personne. La photo doit obligatoirement être de résolution 225x225. 

2. Il faut modifier le fichier `_data/fr/members.yml`. Consultez la structure utilisée par les autres membres qui sont déjà là pour savoir comment. 

3. On peut suivre ce commit comme exemple: https://github.com/ClubCedille/clubcedille.github.io/commit/ddc53c3c2aa5d5082459d42ee4d55a611890f2c4

**Comment by AXDOOMER** [comment]
Aubert et Arthur ont été ajoutés. Faudrait peut-être se faire une page pour les anciens.

**Comment by jalilbengoufa** [comment]
La list des membres est a jour
