### ISSUE TITLE
Add a form to get participants emails 

### ISSUE THREAD

**Issue by ygotame** [ClubCedille/clubcedille.github.io#28]
Add a form to get participants emails so we can inform them about futures events.

**Comment by JulienRobitaille** [comment]
Toujours d'actualité?

**Comment by mikefaille** [comment]
On pourrait le laisser ouvert.
Idéalement, l'outil d'invitation aux évènements devrait pouvoir faire ce travail. De plus, il faudra pouvoir demander un feedback après l'évènement pour l'amélioration continue.
