### ISSUE TITLE
Ajout d'une section avec les sites web des clubs

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/clubcedille.github.io#30]
@ygotame veut une section où on peut afficher les magnifiques sites qu'on a fait pour les autres clubs.

**Comment by JulienRobitaille** [comment]
Ou est la liste de ces sites?

**Comment by mikefaille** [comment]
Ici : https://github.com/ClubCedille/sysadmin/issues/27

**Comment by JulienRobitaille** [comment]
Merci je vais essayer d'ajouter cette section.

**Comment by mikefaille** [comment]
ingenieuses.cedille.club
pontacier.cedille.etsmtl.ca
geniale.ca

**Comment by mikefaille** [comment]
Il y en aura d'autres bientôt ;-)

**Comment by JulienRobitaille** [comment]
J'ai ajouter la section calquée sur la section projets.
Pour l'instant j'ai mis:
ingenieuses.cedille.club
geniale.ca

Le site de pontacier.cedille.etsmtl.ca semble ne pas fonctionner. 
@ygotame @AXDOOMER on peut closer cette issue?

**Comment by AXDOOMER** [comment]
> Bienvenue au autres clubs

Corrige "aux" s'il te plait. Tu devrais peut-être faire de pull requests pour de future modifications afin de nous permettre de regarder avant. 

J'avais imaginé ça sur une autre page (linké dans le section *projets*), mais c'est bien. Merci de ton travail!

Tu peux fermer le issue une fois la faute corrigée (pas besoin de faire un pull request pour elle).

**Comment by mikefaille** [comment]
@JulienRobitaille Je voulais écrire : pontacier.etsmtl.ca

**Comment by JulienRobitaille** [comment]
@AXDOOMER J'ai corrigé la faute. Je vais faire des PR pour les prochaines fois. Je n'avais pas trouvé de procédure.

@mikefaille parfait je vais l'ajouter demain merci !

**Comment by AXDOOMER** [comment]
@JulienRobitaille  Excuse-moi, j'ai vu une autre erreur: "Bienvenu" (ne prend pas un 'e').

**Comment by JulienRobitaille** [comment]
@axdoomer il me semble que quand l'on souhaite la bienvenue il faut un e. Est-tu sûr?

**Comment by AXDOOMER** [comment]
Je crois que tu as raison.
