### ISSUE TITLE
Ajout de site dans le site web

### ISSUE THREAD

**Issue by JulienRobitaille** [ClubCedille/clubcedille.github.io#33]
Je viens de pousser une branche avec le  début du travail sur cette tâches. Je vous invite à cloner et finaliser la fonctionnalité si ça vous intéresse.

Sinon je devrais pouvoir travailler là-dessus d'ici trois semaines.

**Comment by mikefaille** [comment]
Allright. Merci.

Le 15 juin 2017 18:18, "Julien Robitaille" <notifications@github.com> a
écrit :

**Comment by ygotame** [comment]
Travaille est fait dans le PR #36 et fonctionnel
