### ISSUE TITLE
Offer a bilingual website

### ISSUE THREAD

**Issue by samdidos** [ClubCedille/clubcedille.github.io#34]
As we want to welcome contributions among our projects from anybody, it could be great for our visibility to have an english version of our website.

**Comment by BernardClaing** [comment]
La platteforme est ti i18nisé ?

**Comment by BernardClaing** [comment]
""Cedille without cancer and bloat :) "
Sur ma liste des repos je remarque que la ligne de vie (activité) du site web fait un pic puis une ligne plate./\....................................
lol

**Comment by JulienRobitaille** [comment]
@samdidos Toujours d'actualité ? @ygotame
