### ISSUE TITLE
Créer un  google form pour permettre aux gens de demander d'hébergement

### ISSUE THREAD

**Issue by ygotame** [ClubCedille/clubcedille.github.io#37]
Créer un  google form pour permettre aux gens de demander d'hébergement

L'exemple des questions : 

- C'est quoi votre domaine ou sous-domaine  : ex : cedille.club
- Dans le fond c'est quoi leur besoin ?
- Site-web dynamique ou statique ?
- Si dynamique ? CMS  - Ils veulent une installation à neuf avec une thème ou un transfert de leur site vers un nouveau site-web.
- Quel de leur membre sera responsable des communications avec nous?
- Quel genre d'accès ils ont besoin? (Ils prévoient installer des plugins?)
- Quelle est le uptime nécessaire
- Quel sont les délais pour la migration
- Ils veulent une formation post transfert. 
- Quel genre de formation s'attendent-ils?
- et autres

**Comment by mikefaille** [comment]
Je crois que l'on doit limiter le type de site à recevoir afin de faciliter notre scaling puisque c'est nous qui gère tout.
