### ISSUE TITLE
Add Patrick back to the site!

### ISSUE THREAD

**Issue by plaurin84** [ClubCedille/clubcedille.github.io#38]
Hey Guys!! I'm might have been away for a long time, but I'm still the co-founder of the student club! Please add me back to the page ;-) I'm still proud of the club and proud of you guys!! Take care now :+1:

**Comment by mikefaille** [comment]
<3

**Comment by AXDOOMER** [comment]
@plaurin84  On va prendre ta photo Linkedin si ça te dérange pas. Elle a l'air plus professionnel que l'ancienne photo et c'est la direction qu'on prend pour les photos des autres membres aussi qu'on veut remplacer ou ajouter. Sinon tu peux nous soumettre une nouvelle photo. 

@mikefaille  Inquiètes toi pas, je m'en charge. C'est moi qui l'avait ôtée.

**Comment by AXDOOMER** [comment]
Note: [Infos enlevées dans un précédant commit](https://github.com/ClubCedille/clubcedille.github.io/pull/29/files#diff-9b7ece818d70a3344b9889c88660b369L127)

**Comment by plaurin84** [comment]
Merci :-)
