### ISSUE TITLE
Vielle page visible au publique

### ISSUE THREAD

**Issue by notarock** [ClubCedille/clubcedille.github.io#43]
Quelqu'un sait si cette page est encore nécessaire?
cedille.etsmtl.ca/fr/2014/09/26/nouveau-site/
Elle apparait dans les résultats de google.

**Comment by notarock** [comment]
### J'ai explorer un peu...
Visiblement, on a plus de section "news" sur le site. Peut-être qu'il y aurait quelque choses à faire avec ca? 
On pourrait ravoir cette sections news et y mettre une entrée aux quelques semaines, dépendant de ce que l'on fait.
Ca pourrait aussi permettre d'annoncé des événements et activitées.
Ce ne sont que des idées, tant qu'à retirer complètement cette sections... autant l'utilisé.
Je me demande ce que  @jalilbengoufa,  @JulienRobitaille  et/ou @ygotame en pense :thinking:

**Comment by mikefaille** [comment]
Je crois que l'on pourrait mettre des textes ou des résumés d'avancement sur le Blog. Disons que ce n'est pas ce que l'on publierait sur Facebook ou Linkedin alors que nous n'aurons pas de formatage approprié pour afficher du code sur ces dernière plateforme.

**Comment by mikefaille** [comment]
Pour préciser la fréquence de publication et le contenu, on pourrait se donner comme objectifs que chacun des segments de cedille écrive un blog une fois par session/mois afin d'expliquer les avancements ou planification. On pourrait aussi y ajouter un rapport d'expérience technique ou organisationnel à l'image des grandes entreprises tel que [Facebook](https://code.facebook.com/posts/), [Uber](https://eng.uber.com/), [Google](https://developers.googleblog.com/), etc.

**Comment by AXDOOMER** [comment]
La page est encore visible au public. Pourquoi on l'enlève juste pas?
