### ISSUE TITLE
Afficher les anciens membres

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/clubcedille.github.io#50]
Comme décidé à la réunion, on doit afficher les anciens membres en plus petit en dessous de la section des membres actifs.

**Comment by mikefaille** [comment]
Tu vas voir, c'est quand meme cool avoir une trace lorsque tu es ancien.

**Comment by jalilbengoufa** [comment]
J'ai modifier le site pour afficher les anciens membres en cliquant sur un lien, si j'ai oublier qulque'un ou s'il y a un truc qui ne foctionne pas dites le moi. Voici la PR #52 .

**Comment by AXDOOMER** [comment]
Régler de façon élégante. merci @jalilbengoufa . Il manque peut-être des utilisateurs, mais on les ajoutera si ceux-ci se manifestent.
