### ISSUE TITLE
Les formulaires au bas du site ne fonctionnent plus

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/clubcedille.github.io#53]
Ça redirige vers un autre site qui affiche un message d'erreur.

**Comment by jalilbengoufa** [comment]
je viens de tester et ca fonctionne parfaitment, on a recu les emails, peut etre que c'est un probleme avec ton browser.

**Comment by AXDOOMER** [comment]
Ça marche en navigation privée

**Comment by AXDOOMER** [comment]
Ça marche maintenant dans une session normale. Je vais réessayé ce que j'avais fait.

**Comment by AXDOOMER** [comment]
Quand tu mets du HTML + Javascript dans une des boîtes du formulaire, ça fuck. 
```
<!DOCTYPE html>
<html>
<body>

<h2>JavaScript Alert</h2>

<button onclick="myFunction()">Try it</button>

<script>
function myFunction() {
  alert("I am an alert box!");
}
  alert("Boiii!");
</script>

</body>
</html>
```
![Screenshot_2019-06-10_23-05-35](https://user-images.githubusercontent.com/6194072/59241097-4cd70b80-8bd4-11e9-8f21-71e4f55c4d07.png)

**Comment by AXDOOMER** [comment]
Notre API filtre le JavaScript, donc c'est pour ça que ça donne un erreur.

**Comment by notarock** [comment]
Ça fonctionne juste pas quand tu essaie de le briser :)
