### ISSUE TITLE
Changer le logo de Grass Valley

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/clubcedille.github.io#65]
Grass Valley a été acheté par un autre compagnie, donc ils n'appartiennent plus à Belden. 

Mettre leur logo à jour avec:
![GrassValley_Logo RGB](https://user-images.githubusercontent.com/6194072/74770484-57b16800-525a-11ea-9814-8c63eb0954ad.jpg)

**Comment by notarock** [comment]
nice

**Comment by AXDOOMER** [comment]
Le logo est pas parfaitement aligné verticalement, mais bon...
