### ISSUE TITLE
Add new projects

### ISSUE THREAD

**Issue by samdidos** [ClubCedille/clubcedille.github.io#8]
Add some content about our projects
- nETSpresso : add a representing photo
- Add Metaclub
- Add Çynergie
- Add Web sites (?)
- Add Domotic project

**Comment by ygotame** [comment]
Project mirror, formation has been added by @samdidos 

we need to add canoe beton web site and as well as, project of hosting web site for other clubs.

**Comment by AXDOOMER** [comment]
Jardiniot aussi. Ne pas oublier de marquer que c'est une prototype, car à date le "pot" a pas l'air très professionnel, car ce n'est pas finit.

**Comment by AXDOOMER** [comment]
> Add Web sites (?)

Oui, mettre un projet et quand on clique dessus ce sera des liens vers tous les site web qu'on a fait. 

C'est important de l'améliorer, car on s'en sert pour faire de la promotion. Les gens le visitent avant de voter pour nous pour des concours comme ActionTI.

**Comment by mikefaille** [comment]
Pour la partie obscur tel la maintenance des sites et la roadmap techno suivit, je crois qu'il faudrait aussi faire un clin d'oeil à ce niveau afin de rendre justices aux nombreux travaux entrepris avec succès.

**Comment by AXDOOMER** [comment]
On a maintenant une section pour les sites hébergés et une section pour les projets.
